Pullupstream/v0.5.0
0xPolygon/cdk-validium-node pull request #63
Opened 2024-01-30 17:04 UTC by rachit77

2024-02-01 09:49 UTC, arnaubennassar requested changes

2024-02-01 09:49 UTC, arnaubennassar commented on .github/workflows/release.yml
> +name: release
remove this file, it's used for Hermez releases, we should have our own thing

2024-02-01 09:49 UTC, arnaubennassar commented on cmd/main.go
> +		Usage:    "Load default network configuration. Supported values: [`mainnet`, `testnet`, `cardona`, `custom`]",
Didn't realise about this before, but we should only support `custom` option

2024-02-01 09:49 UTC, arnaubennassar commented on config/cardonagenesis.go
> +package config
remove this file

2024-02-01 09:49 UTC, arnaubennassar commented on config/config.go
> +	// FlagNetwork is the flag for the network name. Valid values: ["testnet", "mainnet", "cardona", "custom"].
in the coment, only custom

2024-02-01 09:49 UTC, arnaubennassar commented on config/environments/cardona/example.env
> +ZKEVM_NETWORK = "cardona"
remove:
- config/environments/cardona
- config/environments/testnet
- config/environments/mainnet

2024-02-05 14:13 UTC, christophercampbell submitted a review, later dismissed
LGTM other than missing comment prefix in config file. 

And one comment: I presume the the migration changes are coming from upstream? At some point, once we have installs, we should consider migration files fixed and only accept/write new migrations files.

2024-02-05 14:13 UTC, christophercampbell commented on config/environments/testnet/postgresql.conf
> +-----------------------------
This should be comment line

2024-02-05 14:18 UTC, christophercampbell commented
If the testnet configuration is breaking CI, it might be because the postgres conf file is borked (see above)

2024-02-05 15:20 UTC, Stefan-Ethernal approved these changes

2024-02-05 15:47 UTC, begmaroman approved these changes

2024-02-05 16:28 UTC, vcastellm approved these changes

2024-02-06 09:43 UTC, goran-ethernal approved these changes

2024-02-06 11:49 UTC, arnaubennassar approved these changes

2024-02-06 12:16 UTC, Stefan-Ethernal commented
> If the testnet configuration is breaking CI, it might be because the postgres conf file is borked (see above)

Nope, this is not the case, we have removed all testnet configuration and ZK-EVM node e2e tests are green, only the one which tests DAC is failing (since DA nodes are failing to start up with the error suggesting that contract is not deployed on an expected address):

```bash
2024-02-05T16:41:14.975Z	[31mFATAL[0m	cmd/main.go:104	no contract code at given address
/src/log/log.go:140 github.com/0xPolygon/cdk-data-availability/log.appendStackTraceMaybeArgs()
/src/log/log.go:221 github.com/0xPolygon/cdk-data-availability/log.Fatal()
/src/cmd/main.go:104 main.start()
/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 github.com/urfave/cli/v2.(*Command).Run()
/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 github.com/urfave/cli/v2.(*Command).Run()
/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 github.com/urfave/cli/v2.(*App).RunContext()
/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309 github.com/urfave/cli/v2.(*App).Run()
/src/cmd/main.go:52 main.main()
/usr/local/go/src/runtime/proc.go:250 runtime.main()
	{"pid": 1, "version": "v0.0.3-30-gc030128"}
main.start
```

2024-02-07 08:47 UTC, merged